In [1]:
#import library
import numpy as np

In [2]:
#The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.
#Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object also called as dtype.
# One-dimensional array of some prime numbers
oneD_array = np.array([2,3,5,7,11])
print(oneD_array)
oneD_array

[ 2  3  5  7 11]


array([ 2,  3,  5,  7, 11])

In [43]:
# to check the type of array
type(arr)

numpy.ndarray

In [4]:
#create Two-dimensional array
two_D_array = np.array([[4,5],[8,6]])
print(two_D_array)


[[4 5]
 [8 6]]


In [5]:
two_D_array

array([[4, 5],
       [8, 6]])

In [6]:
# Create a three-dimensional array 
three_D_array = np.array([[[1,2],[3,4]],
                        [[5,6],[7,8]]])
print(three_D_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# Create a four-dimensional array
fourD_array = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],
          [[[1,2],[3,4]],[[5,6],[7,8]]]])
fourD_array



array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [8]:
# for Shape use 'ndarray.shape'.This returns a tuple consisting of array dimensions and can be used to resize the array
array_1 = np.array([[1,2,3],[4,5,6]]) 
print(array_1.shape)


(2, 3)


In [9]:
array_2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]]) 
# print(array_2)
print(array_2.shape)

(4, 2, 3)


In [10]:
array_2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
# for dimension use 'ndarray.dim'.this returns the number of array dimensions
oneD_array = np.array([2,3,5,7,11])
print("Dimensions of 'oneD_array' = ", oneD_array.ndim)


twoD_array = np.array([[4,5],[8,6]])
print("Dimensions of 'twoD_array' = ", twoD_array.ndim)


threeD_array = np.array([[[1,2],[3,4]],
                        [[5,6],[7,8]]])
print("Dimensions of 'threeD_array' = ", threeD_array.ndim)




Dimensions of 'oneD_array' =  1
Dimensions of 'twoD_array' =  2
Dimensions of 'threeD_array' =  3


In [21]:
# For size use 'ndarray.size'. This returns the total number of elements in the array'
integers_array = np.array([0,12,4,5,6,76,5,15,45,4,9,8,41])
print(f"The totaln number in our array 'integers_array' = {integers_array.size}")


two_d_array =  np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in our array two_d_array' =  {two_d_array.size}")

The totaln number in our array 'integers_array' = 13
The total number of elements in our array two_d_array' =  6


In [13]:
# To check the type of array
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)

int64


In [16]:
my_array_1 = np.array([1,2.0,3,4,5,'abc'])
print(my_array.dtype)
my_Array = np.array(['Jai','shoas','sdf'])
print(my_Array.dtype)

int64
<U5


In [17]:
my_array_1

array(['1', '2.0', '3', '4', '5', 'abc'], dtype='<U32')

In [18]:
# changes the data type of an array use 'ndarray.astype'

In [19]:
# Create an array
arr = np.array([2,3,4])
print(arr)
print(arr.dtype)
# Change the datatype of the array to float
arr_ = arr.astype('float64')
print(arr_)
print(arr_.dtype)

[2 3 4]
int64
[2. 3. 4.]
float64


**Different ways of creating an** **ndarray**

**Uninitialized**

In [22]:
# Creating an uninitialized array of a specified shape
uninitialized_array = np.empty([4,3],dtype=int)
print(uninitialized_array)

[[ 94483415513536               0            1605]
 [ 94483393276216 139885059741528  94483393276896]
 [139885059741528 139885059741528               0]
 [              2     12884901888              11]]


**Initialized with zeros**

In [23]:
#Creating zero Array
zeros_array = np.zeros((3,3)) # Default dtype = float
another_zeros_array = np.zeros((4,3) , dtype=int)
print(zeros_array)
print(another_zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


**Initialized with ones**

In [24]:
#Creating Ones Array
ones_array = np.ones((3,3)) # Default dtype = float
another_ones_array = np.ones((2,3) , dtype=int)
print(ones_array)
print(another_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [30]:
bunch_of_ones = np.ones((4,5))
bunch_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
#trying to change the shape of array
bunch_of_ones.shape = (2,10)
bunch_of_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Array from numerical ranges**

In [34]:
# Array with values from 0 to N
array_with_range = np.arange(10)
array_with_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Set start and stop parameters
# Parameters for the function - np.arange(start, stop, step, dtype)
# Default dtype is that of the input given
array_with_range = np.arange(10,30,2) 
array_with_range

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [42]:
# to get the number of evenly spaced values between intervals
# Parameters for the function - np.linespace(start, stop, num, endpoint, retstep, dtype)
# dtype is that of output array
linearly_spaced_values = np.linspace(15,30,9, endpoint = False, retstep = True) 
linearly_spaced_values

(array([15.        , 16.66666667, 18.33333333, 20.        , 21.66666667,
        23.33333333, 25.        , 26.66666667, 28.33333333]),
 1.6666666666666667)